language: python

python:
 - 3.6

install:
 - pip install -r requirements.txt

script:
 - bash run.sh

notifications:
  email:
    recipients:
      - damorim@cin.ufpe.br
      - isb@cin.ufpe.br
      - dgs@cin.ufpe.br      
    on_success: always
    on_failure: always
