language: python

python:
 - 3.6

install:
 - pip install -r requirements.txt

script:
 - bash run.sh

notifications:
  email:
    recipients:
      - docker-fix-finders@googlegroups.com
    on_success: always
    on_failure: always